### PR TITLE
Adds concept description and UI diagram

### PR DESCRIPTION
**Pull request by mbalabanov**

### CODE REVIEW

**Comment by Logi13** [comment]
Have to point in this pull request specifically the changes to .env.development file. 

What you are doing is changing the dev env file to point to a production server. 

This is the purpose of the .env.production file. The .env.development should always point to a development server. 

Very bad things can happen if a dev environment points to your production server!

Also don;t forget that you need to get the work plan approved before working on it.

**Comment by glowkeeper** [comment]
@Logi13 while I agree, in this case, they are developing against a live development service - i.e. the system described in env.production. You can think of it as a development system that's live on the 'net, I s'pose. However, for now @mbalabanov - keep those settings on your local machine for now...i.e. remove your .env.development settings from the PR (just revert the setting and recommit the file)

**Comment by mbalabanov** [comment]
Updated PR to revert dev env to localhost

**Review by glowkeeper — COMMENTED** [review]
Lovely diagrams!

**Review by glowkeeper — DISMISSED** [review]

**Review by glowkeeper — APPROVED** [review]

**Comment by mbalabanov** [comment]
> Have to point in this pull request specifically the changes to .env.development file.
> 
> What you are doing is changing the dev env file to point to a production server.
> 
> This is the purpose of the .env.production file. The .env.development should always point to a development server.
> 
> Very bad things can happen if a dev environment points to your production server!

Hey there, just to let you know, throught all the merging and consolidation, the environment variable has been changed back to the version you didn't find so good. See: https://github.com/boolean-uk/team-dev-frontend-client/blob/main/.env.development

I believe that this was even approved by yourself and/or Lewis at during Wednesday's call.

**Pull request merged**
